2022-12-05T22:29:29.671Z - error: [gme:server:worker:simpleworker:pid_12736:WorkerFunctions:PluginManagerBase] Meta-nodes share the same full name. Will still proceed.. Petri_Net
2022-12-05T22:29:29.870Z - error: [gme:server:worker:simpleworker:pid_12736:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin] Traceback (most recent call last):
  File "C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py", line 12, in <module>

2022-12-05T22:29:29.873Z - error: [gme:server:worker:simpleworker:pid_12736:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin]     from webgme_bindings import WebGME
ModuleNotFoundError: No module named 'webgme_bindings'

2022-12-05T22:29:29.882Z - error: [gme:server:worker:simpleworker:pid_12736:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin] Error: python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1.
    at ChildProcess.<anonymous> (C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\ClassificationPlugin.js:99:37)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2022-12-05T22:29:29.887Z - error: [gme:server:worker:simpleworker:pid_12736:WorkerFunctions] plugin [ClassificationPlugin] failed with error message=python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1., stack=Error: python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1.
    at ChildProcess.<anonymous> (C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\ClassificationPlugin.js:99:37)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2022-12-05T22:29:57.280Z - error: [gme:server:worker:simpleworker:pid_12736:WorkerFunctions:PluginManagerBase] Meta-nodes share the same full name. Will still proceed.. Petri_Net
2022-12-05T22:29:57.409Z - error: [gme:server:worker:simpleworker:pid_12736:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin] Traceback (most recent call last):
  File "C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py", line 12, in <module>

2022-12-05T22:29:57.412Z - error: [gme:server:worker:simpleworker:pid_12736:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin]     from webgme_bindings import WebGME
ModuleNotFoundError: No module named 'webgme_bindings'

2022-12-05T22:29:57.423Z - error: [gme:server:worker:simpleworker:pid_12736:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin] Error: python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1.
    at ChildProcess.<anonymous> (C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\ClassificationPlugin.js:99:37)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2022-12-05T22:29:57.425Z - error: [gme:server:worker:simpleworker:pid_12736:WorkerFunctions] plugin [ClassificationPlugin] failed with error message=python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1., stack=Error: python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1.
    at ChildProcess.<anonymous> (C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\ClassificationPlugin.js:99:37)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2022-12-05T22:31:14.205Z - error: [gme:server:worker:simpleworker:pid_50688:WorkerFunctions:PluginManagerBase] Meta-nodes share the same full name. Will still proceed.. Petri_Net
2022-12-05T22:31:14.370Z - error: [gme:server:worker:simpleworker:pid_50688:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin] Traceback (most recent call last):
  File "C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py", line 12, in <module>

2022-12-05T22:31:14.373Z - error: [gme:server:worker:simpleworker:pid_50688:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin]     from webgme_bindings import WebGME
ModuleNotFoundError: No module named 'webgme_bindings'

2022-12-05T22:31:14.377Z - error: [gme:server:worker:simpleworker:pid_50688:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin] Error: python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1.
    at ChildProcess.<anonymous> (C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\ClassificationPlugin.js:99:37)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2022-12-05T22:31:14.384Z - error: [gme:server:worker:simpleworker:pid_50688:WorkerFunctions] plugin [ClassificationPlugin] failed with error message=python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1., stack=Error: python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1.
    at ChildProcess.<anonymous> (C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\ClassificationPlugin.js:99:37)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2022-12-05T22:32:42.326Z - error: [gme:server:worker:simpleworker:pid_48412:WorkerFunctions:PluginManagerBase] Meta-nodes share the same full name. Will still proceed.. Petri_Net
2022-12-05T22:32:42.565Z - error: [gme:server:worker:simpleworker:pid_48412:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin] Traceback (most recent call last):
  File "C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py", line 12, in <module>

2022-12-05T22:32:42.566Z - error: [gme:server:worker:simpleworker:pid_48412:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin]     from webgme_bindings import WebGME
ModuleNotFoundError: No module named 'webgme_bindings'

2022-12-05T22:32:42.575Z - error: [gme:server:worker:simpleworker:pid_48412:WorkerFunctions:PluginManagerBase:plugin:ClassificationPlugin] Error: python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1.
    at ChildProcess.<anonymous> (C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\ClassificationPlugin.js:99:37)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2022-12-05T22:32:42.582Z - error: [gme:server:worker:simpleworker:pid_48412:WorkerFunctions] plugin [ClassificationPlugin] failed with error message=python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1., stack=Error: python C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\run_plugin.py 5555 "#0e64b9478a114ae6b01b40a43690c2aeb4df355b" "master" "" "" "" exited with code 1.
    at ChildProcess.<anonymous> (C:\Users\rodri\Work\miniproject-petrinet\src\plugins\ClassificationPlugin\ClassificationPlugin.js:99:37)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
